[package]
name = "sort_bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-hex = "0.2.0"
fxhash = "0.2.1"
num = "0.4.1"
plotters = "0.3.5"
rand = "0.8.5"
